### ISSUE TITLE
Pool Enhancement 

### ISSUE THREAD

**Issue by yogyrahmawan** [iwanbk/rimcu#11]
Proposal 
### Add new fields in pool struct that contains 
* min idle connection .  
* max active connection . if 0 unlimited. represent total connection 
* idle time out . for closing connection if idle for certain period. 
* active to identify active connections 

### In conn struct 
* add createdAt and lastUsedAt 
* create goroutine in pool to check obsolete connections by using above params 

### in get 
* check if connections is obsolete or not by using parameter idle timeout and send Do("PING") to redis. 
* if there is available connections in iddle connecitons, use it. otherwise create connection 

### in put 
* if active > maxActive, remove it 
* otherwise add it into iddle connections

**Comment by iwanbk** [comment]
Hi  @yogyrahmawan thanks for the proposal.

It seems that the proposal touch many things at once.


Some comments on the proposal

> min idle connection .
> add createdAt 
> create goroutine in pool to check obsolete connections by using above params

don't think we need all the above, let me know your reasons.

>  send Do("PING") to redis.

should be optional.

Anyway, let's pick one simple thing that you're most confident about and give more details if any, like:
- why we need it
- more details on the plan (if any)
- ...

**Comment by yogyrahmawan** [comment]
```
min idle connection .
add createdAt
create goroutine in pool to check obsolete connections by using above params
```
Min idle connection is to create ready connection to use. 
createdAt is to check when the connection created . That will need to identify whether connection is stale or not based on idle time out . 
For goroutine, we can remove it and check it everytime we get connection from pool . 

```
should be optional.
```
Aggreed 

I think first step is to implement ping and add optional params for that . 
Then implement 
```
max active connection . if 0 unlimited. represent total connection
idle time out
```
and modify get and put

**Comment by iwanbk** [comment]
> I think first step is to implement ping and add optional params for that .
> Then implement

> max active connection . if 0 unlimited. represent total connection
> idle time out

OK, lets do this.
But i'm not sure about the `optional param`

> and modify get and put

what kind of modification?

**Comment by iwanbk** [comment]
closed for inactivity
